-- Pace Blueprint's own tables, translated from the Postgres draft in
-- `planning/03-engineering-requirements.md` "DB schema (draft)" and `docs/architecture.md`
-- "Planned — DB schema" into D1's SQLite dialect.
--
-- ============================================================================================
-- WHAT SQLITE DOES NOT HAVE, AND WHAT WAS DONE INSTEAD
-- ============================================================================================
--
-- 1. NO ROW-LEVEL SECURITY. This is the big one. The Postgres design leaned on
--    `user_id = auth.uid()` policies as the *last* line of defence, so a Worker bug could not
--    leak another user's rows. SQLite has no policy system at all: D1 executes whatever SQL the
--    Worker sends, as the Worker. Authorization therefore lives entirely in Worker code —
--    `workers/src/lib/store.ts` takes `userId` from the better-auth session and binds it into
--    every single statement's WHERE clause. There is no second net. See that file's header and
--    `docs/architecture.md` "Authorization without RLS".
--
-- 2. NO SECURITY DEFINER FUNCTIONS / NO STORED PROCEDURES, so the atomic quota RPC could not be
--    ported as an RPC, and `pg_advisory_xact_lock` has no equivalent either. The quota gate is
--    instead ONE conditional `INSERT ... SELECT ... WHERE (SELECT count(*) ...) < limit`
--    statement (see `reserve` in `workers/src/lib/store.ts`). That is genuinely atomic *here*
--    even though the same trick is NOT sufficient in Postgres: Postgres MVCC lets two concurrent
--    statements each evaluate the count subquery before either commits, whereas SQLite takes an
--    exclusive write lock for the duration of a write statement and D1 serializes all queries to
--    a database through a single Durable Object. The count subquery therefore cannot observe a
--    stale snapshot. `UNIQUE (user_id, idempotency_key)` below is the unconditional backstop.
--
-- 3. NO `jsonb`. `plans.plan` is TEXT with a `json_valid()` CHECK (SQLite's JSON1 extension is
--    compiled into D1). Reads `JSON.parse()` in Worker code. Nothing queries *inside* the plan
--    document, so losing jsonb's operators and GIN indexes costs nothing.
--
-- 4. NO `text[]`. `intake_responses.injuries` is a JSON array in TEXT, `json_valid()`-checked.
--    The closed set is enforced in Worker code against `planTypes.ts`'s `InjuryFlag`.
--
-- 5. NO ENUM TYPES. Every Postgres enum became TEXT + a CHECK constraint listing the same
--    members. Same rejection behaviour, worse error messages, and adding a member is a migration
--    that rebuilds the table rather than `ALTER TYPE ... ADD VALUE`.
--
-- 6. NO `timestamptz` / NO `uuid`. Timestamps are ISO-8601 UTC TEXT, which sorts and compares
--    lexicographically exactly as chronological order (this is load-bearing: the period-window
--    and stale-reservation comparisons below are string comparisons). Ids are TEXT, minted with
--    `crypto.randomUUID()` in Worker code. (better-auth's own tables in `0001` use INTEGER
--    epoch-millis instead — that is its adapter's choice, not ours, and the two conventions
--    deliberately do not mix across the table boundary.)
--
-- 7. NO PARTIAL-UPDATE PRIVILEGE MODEL. Postgres would have expressed "`plans` grants select and
--    insert, never update or delete" as RLS grants. Here that rule is a BEFORE UPDATE trigger
--    that aborts any write to an already-terminal row (see the bottom of this file).
-- ============================================================================================

PRAGMA foreign_keys = ON;

-- --------------------------------------------------------------------------------------------
-- profiles — app-owned profile data, keyed 1:1 to better-auth's `user`.
--
-- The Postgres draft had `profiles (id -> auth.users, ...)` because Supabase's `auth.users` lives
-- in a schema you may not add columns to. The same separation is kept here for a different but
-- equally real reason: `user` is better-auth's table, its shape is regenerated by better-auth's
-- CLI, and app columns added to it would be fighting a code generator on every version bump.
-- --------------------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS profiles (
  user_id      TEXT PRIMARY KEY NOT NULL REFERENCES user (id) ON DELETE CASCADE,
  display_name TEXT,
  created_at   TEXT NOT NULL,
  updated_at   TEXT NOT NULL
);

-- --------------------------------------------------------------------------------------------
-- intake_responses — one row per user, upserted by the intake screen.
--
-- Column semantics are copied verbatim from the draft schema's comments because they are product
-- rules, not implementation notes:
--   age              required — max HR = 220 − age, and 50+ forces a 3-week deload cadence, so
--                    no HR zone is computable without it.
--   goal_time_sec    drives RACE-PACE sessions ONLY. Never everyday training paces.
--   recent_perf_*    drives EVERY training pace. Absent → the plan emits no numeric pace at any
--                    tier, only effort language. This is why the design's "readout bracket" can
--                    never render a lie.
--   injuries         closed-set flags (`planTypes.ts`'s `InjuryFlag`). These, and only these,
--                    drive the deterministic safety rules.
--   injury_notes     free text. Context for the model on paid tiers. Never gates safety.
-- --------------------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS intake_responses (
  user_id              TEXT PRIMARY KEY NOT NULL REFERENCES user (id) ON DELETE CASCADE,
  goal                 TEXT    NOT NULL,
  age                  INTEGER NOT NULL CHECK (age >= 10 AND age <= 100),
  experience           TEXT    NOT NULL CHECK (
                         experience IN ('new', 'some', 'regular', 'experienced', 'competitive')
                       ),
  days_per_week        INTEGER NOT NULL CHECK (days_per_week >= 1 AND days_per_week <= 7),
  weekly_km            REAL    NOT NULL CHECK (weekly_km >= 0),

  race_distance        TEXT    CHECK (race_distance IN ('5k', '10k', 'half', 'marathon')),
  race_date            TEXT,
  goal_time_sec        INTEGER CHECK (goal_time_sec IS NULL OR goal_time_sec > 0),
  recent_perf_distance TEXT    CHECK (recent_perf_distance IN ('5k', '10k', 'half', 'marathon')),
  recent_perf_time_sec INTEGER CHECK (recent_perf_time_sec IS NULL OR recent_perf_time_sec > 0),

  -- JSON array of InjuryFlag. `text[]` has no SQLite equivalent (translation 4 above).
  injuries             TEXT    NOT NULL DEFAULT '[]' CHECK (json_valid(injuries)),
  injury_notes         TEXT,
  updated_at           TEXT    NOT NULL,

  -- A recent performance is a (distance, time) pair or nothing at all. Half of one is a bug that
  -- would silently disable every pace in the plan, so the database refuses to store it.
  CHECK (
    (recent_perf_distance IS NULL AND recent_perf_time_sec IS NULL)
    OR (recent_perf_distance IS NOT NULL AND recent_perf_time_sec IS NOT NULL)
  )
);

-- --------------------------------------------------------------------------------------------
-- subscriptions — one row per user, written ONLY by `purchase-tier`.
--
-- DELIBERATE DEVIATION FROM THE DRAFT: the draft lists `(user_id, tier, period_start, period_end,
-- source)`. `period_start`/`period_end` are NOT stored here, because storing them contradicts the
-- rule they appear next to — `docs/reference/plan-generation.md` "Quotas" requires periods to be
-- "computed arithmetically at read time from the purchase-day anchor ... No cron, no rollover
-- write." Two stored boundary columns can only stay correct if something rolls them over. What is
-- stored is the anchor itself, `purchased_at`; `currentPeriod(anchorDate, now)` in
-- `src/lib/quotaPeriod.ts` derives the window. `purchase-tier` still RETURNS
-- `{ periodStart, periodEnd }` — the client contract is unchanged, the values are just computed.
--
-- `source` exists so v2's real IAP is a value change, not a schema rewrite: same route, same
-- table write, `'dummy'` becomes `'revenuecat'` once a receipt is verified.
-- --------------------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS subscriptions (
  user_id      TEXT PRIMARY KEY NOT NULL REFERENCES user (id) ON DELETE CASCADE,
  tier         TEXT NOT NULL CHECK (tier IN ('pro', 'elite')),
  purchased_at TEXT NOT NULL,
  source       TEXT NOT NULL CHECK (source IN ('dummy', 'revenuecat')),
  status       TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'cancelled')),
  created_at   TEXT NOT NULL,
  updated_at   TEXT NOT NULL
);

-- `free` is deliberately not a storable tier: it is the ABSENCE of a subscription row, exactly as
-- `docs/reference/plan-generation.md` states ("A user with no `subscriptions` row is `free`").
-- One representation of free, so a `tier = 'free'` row can never disagree with no row at all.

-- --------------------------------------------------------------------------------------------
-- plans — the quota ledger and the plan store, in one table.
--
-- There is deliberately NO separate counter table: a counter is a second copy of a number that
-- can drift away from the rows it counts (`docs/architecture.md`: "There is no separate counter
-- table to drift out of sync with `plans` itself").
--
-- LIFECYCLE. A row is born `reserved` (that insert IS the quota reservation, translation 2
-- above), then goes to exactly one terminal state:
--   settled  — generation finished; `plan` holds the immutable document.
--   released — generation failed server-side (model error, timeout, crash). The slot goes back.
-- A `reserved` row older than the Worker's reservation TTL is treated as dead by the count, so a
-- Worker that dies mid-generation cannot permanently consume a slot. That is what replaces the
-- stale-reservation cron the Postgres design would have needed.
--
-- `counts_against_quota` is set at settle time, and encodes the fallback rule from
-- `docs/reference/plan-generation.md` "Quotas": a fallback is quota-EXEMPT (0) for the first
-- `FALLBACK_EXEMPTION_CAP` fallbacks in the period; past the cap, addendum R-B says the 4th+
-- fallback KEEPS its already-reserved slot (1). Nobody is refused a plan either way.
-- --------------------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS plans (
  id                   TEXT PRIMARY KEY NOT NULL,
  user_id              TEXT NOT NULL REFERENCES user (id) ON DELETE CASCADE,
  tier_at_generation   TEXT NOT NULL CHECK (tier_at_generation IN ('free', 'pro', 'elite')),
  -- NULL until settled: a reservation does not yet know which engine produced it.
  engine               TEXT CHECK (engine IS NULL OR engine IN ('template', 'hybrid', 'ai')),
  goal_type            TEXT NOT NULL CHECK (goal_type IN ('race', 'duration')),
  race_distance        TEXT CHECK (race_distance IS NULL
                                   OR race_distance IN ('5k', '10k', 'half', 'marathon')),
  race_date            TEXT,
  duration_weeks       INTEGER CHECK (duration_weeks IS NULL OR duration_weeks > 0),

  -- `jsonb` → TEXT + json_valid (translation 3 above). NULL while reserved.
  plan                 TEXT CHECK (plan IS NULL OR json_valid(plan)),
  is_fallback          INTEGER NOT NULL DEFAULT 0 CHECK (is_fallback IN (0, 1)),
  idempotency_key      TEXT NOT NULL,

  status               TEXT NOT NULL DEFAULT 'reserved'
                         CHECK (status IN ('reserved', 'settled', 'released')),
  counts_against_quota INTEGER NOT NULL DEFAULT 1 CHECK (counts_against_quota IN (0, 1)),
  release_reason       TEXT,

  created_at           TEXT NOT NULL,
  settled_at           TEXT,

  -- The idempotency backstop. A retried request that races past the in-Worker replay lookup is
  -- rejected here by the database, and the Worker re-reads the winning row instead of generating
  -- (and charging) a second plan.
  UNIQUE (user_id, idempotency_key),

  -- A settled plan must carry its document and its engine; a released one must say why. Rows
  -- that lie about their own lifecycle are what make a quota ledger untrustworthy.
  CHECK (status <> 'settled' OR (plan IS NOT NULL AND engine IS NOT NULL AND settled_at IS NOT NULL)),
  CHECK (status <> 'released' OR release_reason IS NOT NULL)
);

-- The quota count's exact predicate: user + counting rows + window. Column order matches it.
CREATE INDEX IF NOT EXISTS idx_plans_quota
  ON plans (user_id, counts_against_quota, status, created_at);

-- My Plans (newest first).
CREATE INDEX IF NOT EXISTS idx_plans_user_created
  ON plans (user_id, created_at DESC);

-- --------------------------------------------------------------------------------------------
-- The immutability guard (translation 7 above).
--
-- `planning/03-engineering-requirements.md` "Security requirements": "**Plans are never
-- user-deletable.** `plans` RLS grants select/insert only, on purpose — no update, no delete.
-- Count-based quota depends on this (a delete policy would let a user reset their own count,
-- which Echo V1 learned the hard way)."
--
-- Postgres would enforce that with grants. Here it is a trigger, which has one advantage over the
-- grant it replaces: it binds the Worker's own service-level access too, not just the client's.
-- The reserved → settled/released transition is allowed; a write to an already-terminal row is
-- not, whoever issues it.
--
-- Deletes are intentionally NOT blocked: `delete-account` must be able to erase a user's plans,
-- and the FK cascade from `user` is the mechanism. "Never user-deletable" is enforced by there
-- being no route that deletes a single plan — see `workers/src/index.ts`'s route table.
-- --------------------------------------------------------------------------------------------
CREATE TRIGGER IF NOT EXISTS plans_are_immutable_once_terminal
BEFORE UPDATE ON plans
FOR EACH ROW
WHEN OLD.status IN ('settled', 'released')
BEGIN
  SELECT RAISE(ABORT, 'plans are immutable once settled or released');
END;
